parameters:

services:
#    _instanceof:
#        CarlosChininin\ApiBundle\AbstractApi:
#            tags: [ 'carloschininin.api_service' ]

    CarlosChininin\ApiBundle\AbstractApi:
        public: true
        tags: [ 'carloschininin.api_service' ]
