parameters:

services:
#    _instanceof:
#        CarlosChininin\ApiBundle\AbstractApi:
#            tags: [ 'carloschininin.api_service' ]

    CarlosChininin\ApiBundle\AbstractApi:
        tags: [ 'carloschininin.api_service' ]
    CarlosChininin\ApiBundle\AbstractAuthApi:
        tags: [ 'carloschininin.api_service' ]
